[build]
  command = "npm run build"
  publish = "dist"
  NODE_ENV = "16.13.1"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/cards"
  to = "https://cards.cityvis.io"
  status = 301
  force = true